export const category = {
    categories: [
        {
            "id": "1",
            "title": "10k Ohm 0.25W Metal Film Resistor (Pack of 100)",
            "countInStock": 13,
            "price": 98,
            "image": "https://robu.in/wp-content/uploads/2019/09/10k-Ohm-0.25W-Metal-Film-Resistor-1-314x252.png",
            "about":"10k Ohm 0.25W Metal Film Resistor (Pack of 100) is a pack of 100pcs of 10k Ohm 0.25W Metal Film Resistor. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project. These are high-quality resistors with a 1% tolerance. These resistors are perfect for use in any DIY electronics project. These resistors are perfect for use in any DIY electronics project."
        },
        {
            "id": "2",
            "title": "100Pcs. 1/4W Metal Film Resistors Assortment for DIY Electronic Projects and Experiments",
            "countInStock": 7,
            "price": 1060,
            "image": "https://robu.in/wp-content/uploads/2019/03/100pcs-Resistor-Kit-4-314x252.jpg",
            "about":"Embark on your electronic journey with confidence using our 1/4W Metal Film Resistors Assortment, tailored for DIY enthusiasts and seasoned experimenters alike. Whether you're a curious beginner or a seasoned pro, our meticulously curated selection of resistors empowers you to tackle projects with precision and reliability.            Crafted with quality and precision in mind, each resistor in our assortment is designed to deliver consistent performance, ensuring stable operation across a wide range of electronic applications. From basic circuits to intricate experiments, these resistors provide the essential building blocks for your creative endeavors. With a variety of resistance values conveniently packaged in one assortment, you'll have the flexibility to experiment and innovate without limitations. Whether you're tinkering with Arduino projects, building custom circuits, or delving into the world of robotics, our assortment offers the versatility you need to bring your ideas to life.            Designed for convenience and practicality, our assortment comes neatly organized, making it easy to find the perfect resistor for your project. Say goodbye to rummaging through cluttered drawers and hello to efficiency and productivity. Join countless DIY enthusiasts who trust our 1/4W Metal Film Resistors Assortment for their electronic projects and experiments. With reliability, precision, and convenience at your fingertips, the possibilities are endless. Start your journey today and unleash your creativity with confidence."
        },
        {
            "id": "3",
            "title": "ULN2003 7 Darlington Transistor Arrays IC DIP-16 Package",
            "countInStock": 70,
            "price": 25,
            "image": "https://robu.in/wp-content/uploads/2021/12/Screenshot-2023-04-26-171310.png",
            "about":"The ULN2003 7 Darlington Transistor Arrays IC DIP-16 is a versatile integrated circuit that consists of seven high-voltage, high-current Darlington transistor pairs. Each pair can handle a continuous current of up to 500mA and withstand a voltage of up to 50V. This IC is commonly used for driving various loads such as relays, motors, solenoids, and LEDs. With its built-in flyback diodes, it provides protection against back EMF generated by inductive loads. The DIP-16 package makes it easy to integrate into your electronic projects. Whether you're building robotics projects, automation systems, or motor control circuits, the ULN2003 IC offers a reliable and efficient solution for driving high-power loads."
        },
        {
            "id": "4",
            "title": "SN74LS47N BCD to 7-Segment Decoder/Driver IC (7447 IC) DIP-16 Package",
            "countInStock": 55,
            "price": 45,
            "image": "https://robu.in/wp-content/uploads/2021/10/DIP-16-IC-314x252.jpg",
            "about":"The SN74LS47N BCD to 7-Segment Decoder/Driver IC (7447 IC) is a versatile integrated circuit that simplifies the process of driving 7-segment displays. It takes a binary-coded decimal (BCD) input and decodes it into the corresponding 7-segment display outputs. This IC is commonly used in digital clock circuits, scoreboards, and other applications that require numerical displays. The DIP-16 package makes it easy to integrate into your electronic projects. Whether you're building digital counters, frequency meters, or other digital display systems, the SN74LS47N IC offers a reliable and efficient solution for driving 7-segment displays.",
        },
        {
            "id": "5",
            "title": "RP2040 Microcontroller IC by Raspberry PI",
            "countInStock": 4,
            "price": 72,
            "image": "https://robu.in/wp-content/uploads/2021/06/Raspberry-PI-RP2040_Microcontroller-IC_38675_1-314x252.jpeg",
            "about":"The RP2040 Microcontroller IC by Raspberry PI is a powerful and versatile microcontroller that is designed to provide a high-performance solution for a wide range of embedded applications. It features a dual-core ARM Cortex-M0+ processor with a clock speed of up to 133MHz, providing the processing power needed to handle complex tasks. The RP2040 also includes 264KB of RAM, 2MB of flash memory, and a wide range of I/O options, making it suitable for a variety of projects. Whether you're building IoT devices, robotics projects, or other embedded systems, the RP2040 Microcontroller IC offers the performance and flexibility you need to bring your ideas to life. The RP2040 is designed to be easy to use, with a wide range of development tools and resources available to help you get started. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the RP2040. With its powerful features, flexible design, and extensive support, the RP2040 Microcontroller IC is the ideal choice for your next embedded project."
        },
        {
            "id": "6",
            "title": "ATmega328P-U PDIP-28 Microcontroller",
            "countInStock": 64,
            "price": 475,
            "image": "https://robu.in/wp-content/uploads/2018/11/162204-314x252.jpg",
            "about":"The ATmega328P-U PDIP-28 Microcontroller is a versatile and powerful microcontroller that is designed to provide a high-performance solution for a wide range of embedded applications. It features a high-speed 8-bit AVR RISC-based microcontroller core with a clock speed of up to 20MHz, providing the processing power needed to handle complex tasks. The ATmega328P also includes 32KB of flash memory, 2KB of SRAM, and 1KB of EEPROM, making it suitable for a variety of projects. Whether you're building IoT devices, robotics projects, or other embedded systems, the ATmega328P Microcontroller offers the performance and flexibility you need to bring your ideas to life. The ATmega328P is designed to be easy to use, with a wide range of development tools and resources available to help you get started. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the ATmega328P. With its powerful features, flexible design, and extensive support, the ATmega328P Microcontroller is the ideal choice for your next embedded project."
        },
        {
            "id": "7",
            "title": "34 mm Circular Heat Sink for Motor ",
            "countInStock": 50,
            "price": 89,
            "image": "https://robu.in/wp-content/uploads/2020/12/heat-sink-for-motor-2-314x252.jpg",
            "about":"The 34 mm Circular Heat Sink for Motor is designed to provide effective cooling for your motor. It features a circular design with a 34mm diameter, making it suitable for a wide range of motors. The heat sink is made from high-quality aluminum, which provides excellent thermal conductivity and durability. Whether you're building robotics projects, automation systems, or other motor-driven applications, the 34 mm Circular Heat Sink offers a reliable and efficient solution for keeping your motor cool. With its lightweight and compact design, it's easy to install and integrate into your projects. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the 34 mm Circular Heat Sink. With its powerful features, flexible design, and extensive support, the 34 mm Circular Heat Sink is the ideal choice for your next motor cooling project."
        },
        {
            "id": "8",
            "title": "Waveshare Dedicated Aluminum Heatsink for Raspberry Pi Zero Series, Zero / Zero 2 W",
            "countInStock": 150,
            "price": 289,
            "image": "https://robu.in/wp-content/uploads/2023/09/SKU-1704464-314x252.png",
            "about":"The Waveshare Dedicated Aluminum Heatsink for Raspberry Pi Zero Series, Zero / Zero 2 W is designed to provide effective cooling for your Raspberry Pi Zero. It features a dedicated design that perfectly fits the Raspberry Pi Zero and Zero 2 W, ensuring optimal thermal performance. The heatsink is made from high-quality aluminum, which provides excellent thermal conductivity and durability. Whether you're building IoT devices, robotics projects, or other embedded systems, the Waveshare Dedicated Aluminum Heatsink offers a reliable and efficient solution for keeping your Raspberry Pi Zero cool. With its lightweight and compact design, it's easy to install and integrate into your projects. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the Waveshare Dedicated Aluminum Heatsink. With its powerful features, flexible design, and extensive support, the Waveshare Dedicated Aluminum Heatsink is the ideal choice for your next Raspberry Pi Zero cooling project."
        },
        {
            "id": "9",
            "title": "5A 3 Pin SPDT Toggle Switch",
            "countInStock": 150,
            "price": 69,
            "image": "https://robu.in/wp-content/uploads/2019/12/5A-3-Pin-SPDT-Toggle-Switch-4-314x252.jpg",
            "about":"The 5A 3 Pin SPDT Toggle Switch is a versatile switch that is designed to provide reliable and efficient control for a wide range of applications. It features a single-pole, double-throw (SPDT) configuration, making it suitable for a variety of switching tasks. The switch is rated for a maximum current of 5A, making it suitable for a wide range of electronic projects. Whether you're building robotics projects, automation systems, or other applications, the 5A 3 Pin SPDT Toggle Switch offers a reliable and efficient solution for your switching needs. With its durable construction and compact design, it's easy to install and integrate into your projects. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the 5A 3 Pin SPDT Toggle Switch. With its powerful features, flexible design, and extensive support, the 5A 3 Pin SPDT Toggle Switch is the ideal choice for your next switching project."
        },
        {
            "id": "10",
            "title": "Mini MTS-203 6-Pin DPDT 6A 125VAC Toggle",
            "countInStock": 17,
            "price": 150,
            "image": "https://robu.in/wp-content/uploads/2019/11/Mini-MTS-203-6-Pin-DPDT-6A-125VAC-Toggle-Switch-2-314x252.jpg",
            "about":"The Mini MTS-203 6-Pin DPDT 6A 125VAC Toggle Switch is a versatile switch that is designed to provide reliable and efficient control for a wide range of applications. It features a double-pole, double-throw (DPDT) configuration, making it suitable for a variety of switching tasks. The switch is rated for a maximum current of 6A at 125VAC, making it suitable for a wide range of electronic projects. Whether you're building robotics projects, automation systems, or other applications, the Mini MTS-203 Toggle Switch offers a reliable and efficient solution for your switching needs. With its durable construction and compact design, it's easy to install and integrate into your projects. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the Mini MTS-203 Toggle Switch. With its powerful features, flexible design, and extensive support, the Mini MTS-203 Toggle Switch is the ideal choice for your next switching project."
        },
        {
            "id": "11",
            "title": "GX-16 4-Pin Metal Aviation Plug Male and Female Panel Connector",
            "countInStock": 87,
            "price": 134,
            "image":"https://robu.in/wp-content/uploads/2019/08/GX-16-4-Pin-Metal-Aviation-Plug-Male-and-Female-Panel-Connector-1-314x252.jpg",
            "about":"The GX-16 4-Pin Metal Aviation Plug Male and Female Panel Connector offers robust connectivity for a variety of applications. Crafted with high-quality metal, it ensures durability and reliability. Its 4-pin design caters to diverse electronic systems, providing versatility. Installation is effortless on panels or enclosures, guaranteeing secure connections. Both male and female connectors ensure seamless integration. Its rugged construction and weather-resistant design make it suitable for harsh environments. Enjoy reliable connections, easy installation, and peace of mind in aerospace, DIY electronics, industrial machinery, automotive, and marine projects."
        },
        {
            "id": "12",
            "title": "2 Pins 3.96mm Pitch JST-VH Connector With Housing (Pack of 10)",
            "countInStock": 9,
            "price": 41,
            "image":"https://robu.in/wp-content/uploads/2019/08/edited529583-314x252.png",
            "about":"The 2 Pins 3.96mm Pitch JST-VH Connector With Housing (Pack of 10) is a versatile connector that is designed to provide reliable and efficient connectivity for a wide range of applications. It features a 3.96mm pitch, making it suitable for a variety of electronic projects. The connector is rated for a maximum current of 7A, making it suitable for a wide range of applications. Whether you're building robotics projects, automation systems, or other applications, the 2 Pins 3.96mm Pitch JST-VH Connector offers a reliable and efficient solution for your connectivity needs. With its durable construction and compact design, it's easy to install and integrate into your projects. Whether you're a beginner or an experienced developer, you'll find everything you need to start building with the 2 Pins 3.96mm Pitch JST-VH Connector. With its powerful features, flexible design, and extensive support, the 2 Pins 3.96mm Pitch JST-VH Connector is the ideal choice for your next connectivity project."
        }
    ]
}